/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    HuangXuKangSidebar: [
        {
            type: "autogenerated",
            dirName: ".",
        },
    ],
};

module.exports = sidebars;
